Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace Sana06.Models
{
    public class ApplicationDbContext :DbContext
    {
        public DbSet<deer> Deers { get; set; }
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options) { }
    }
}

Models/ErrorViewModel.cs
namespace Sana06.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/deer.cs
namespace Sana06.Models
{
    public class deer
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Years { get; set; }
        public string favorite_threat { get; set; }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Sana06.Models;

namespace Sana06.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Contacts()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/deerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Sana06.Models;

namespace Sana06.Controllers
{
    public class deerController : Controller
    {
        private readonly ApplicationDbContext _context;

        public deerController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: deer
        public async Task<IActionResult> Index()
        {
            return View(await _context.Deers.ToListAsync());
        }

        // GET: deer/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deer = await _context.Deers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deer == null)
            {
                return NotFound();
            }

            return View(deer);
        }

        // GET: deer/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: deer/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Years,favorite_threat")] deer deer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(deer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(deer);
        }

        // GET: deer/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deer = await _context.Deers.FindAsync(id);
            if (deer == null)
            {
                return NotFound();
            }
            return View(deer);
        }

        // POST: deer/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Years,favorite_threat")] deer deer)
        {
            if (id != deer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(deer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!deerExists(deer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(deer);
        }

        // GET: deer/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var deer = await _context.Deers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deer == null)
            {
                return NotFound();
            }

            return View(deer);
        }

        // POST: deer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var deer = await _context.Deers.FindAsync(id);
            if (deer != null)
            {
                _context.Deers.Remove(deer);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool deerExists(int id)
        {
            return _context.Deers.Any(e => e.Id == id);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "Our story";
}


<div class="about-santa">
    <div class="about-santa__header">
        <h1 class="title">🎅 About Santa & His Reindeer 🦌</h1>
        <div class="subtitle">
            Santa Claus, also known as Saint Nicholas, has been delivering gifts to children around the world for centuries. His legendary sleigh is powered by magical
            reindeer, guiding him through snowy skies on Christmas Eve.
        </div>
    </div>
    <div class="about-santa__raindeers">
        <h2 class="title">🦌 Meet Santa’s Reindeer</h2>
        <ul class="list">
            <li class="list__item"><span>Dasher</span> – The fastest reindeer, leading the way with speed and agility.</li>
            <li class="list__item"><span>Dancer</span> – A graceful performer, always ready to twirl through the skies.</li>
            <li class="list__item"><span>Prancer</span> – Elegant and strong, with a love for winter fun.</li>
            <li class="list__item"><span>Vixen</span> – Clever and quick-witted, always full of surprises.</li>
            <li class="list__item"><span>Comet</span> – The cool and calm navigator of the team.</li>
            <li class="list__item"><span>Cupid</span> – The bringer of love and holiday cheer.</li>
            <li class="list__item"><span>Donner</span> – Strong and bold, ready to power through snowstorms.</li>
            <li class="list__item"><span>Blitzen</span> – Lightning-fast and full of energy.</li>
            <li class="list__item"><span>Rudolph</span> – The famous red-nosed reindeer, leading Santa’s sleigh with his glowing nose.</li>
        </ul>
    </div>

    <div class="about-santa__prepare">
        <h2 class="title">🎄 How They Prepare for Christmas</h2>
        <div class="text">
            Santa’s reindeer spend the year training at the North Pole, staying in top shape for their big night. They eat magical oats, practice flying in winter
            storms, and even enjoy fun games to keep their spirits high!
        </div>
        <div class="text">
            On Christmas Eve, they gear up, get their bells polished, and wait for Santa’s signal to take off into the night sky, spreading joy across the world. 🎁✨
        </div>
    </div>
</div>

Views/Home/Contacts.cshtml
@{
    ViewData["Title"] = "Our contacts";
}


<div class="contact">
    <div class="contact__header header-contact">
        <h1 class="header-contact__title">🎅 Contact Santa’s Reindeer 🦌</h1>
        <div class="header-contact__welcome">
            Welcome to the official contact page of Santa’s magical reindeer! Whether you want to send a message to your favorite reindeer or just say hello, you're in
            the right place!
        </div>
    </div>
    <div class="contact__info info-contact">
        <div class="info-contact__address">
            <span>📍 North Pole Reindeer Stables</span>
            <span>❄️ Santa’s Village, Arctic Circle</span>
        </div>
        <div class="info-contact__tel">📞 Reindeer Hotline: +1-800-XMAS-FLY</div>
        <div class="info-contact__email">📧 Email: reindeer@santasleigh.com</div>
    </div>
    <div class="contact__raindeers">
        <h2 class="raindeer__title">🦌 Meet the Team & Their Mailboxes:</h2>
        <ul class="raindeer-mailboxes">
            <li class="raindeer-mailboxes__item"><span>📩 Dasher</span> – Fastest of them all! Loves letters about races and adventures.</li>
            <li class="raindeer-mailboxes__item"><span>📩 Dancer</span> – The performer! Send dance moves or holiday jingles.</li>
            <li class="raindeer-mailboxes__item"><span>📩 Prancer</span> – The elegant one! Loves compliments and fashion tips.</li>
            <li class="raindeer-mailboxes__item"><span>📩 Vixen</span> – The clever one! Send riddles and fun challenges.</li>
            <li class="raindeer-mailboxes__item"><span>📩 Comet</span> – The cool and calm guide! Loves space facts and jokes.</li>
            <li class="raindeer-mailboxes__item"><span>📩 Cupid</span> – The matchmaker! Loves holiday love stories and kind wishes.</li>
            <li class="raindeer-mailboxes__item"><span>📩 Donner</span> – The strong one! Loves workout tips and power snacks.</li>
            <li class="raindeer-mailboxes__item"><span>📩 Blitzen</span> – The lightning-fast reindeer! Loves weather facts and thunder jokes.</li>
            <li class="raindeer-mailboxes__item"><span>📩 Rudolph</span> – The bright-nosed hero! Loves glow-in-the-dark artwork and kind words.</li>
        </ul>
    </div>
    <div class="contact__endtext">
        💌 Send a Letter to the Reindeer! Write your message, and Santa’s elves will make sure it reaches the right reindeer! 📮 Mailing Address: 🎄 Santa’s Reindeer
        Stables 🎅 North Pole, Arctic Circle 🎁 Secret Tip: If you leave a carrot and a note on Christmas Eve, you might just get a reply! 😉 Happy Holidays! 🎄✨
    </div>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>See secrets of <a href="https://learn.microsoft.com/aspnet/core">building with Web Santa`s deers</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sana06</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Sana06.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="wrapper">
        <header class="header">
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow ">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                        <img src="~/img/deer logo.jpg" alt="deer`s logo" />
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Contacts">Contacts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Home" asp-action="About">About us</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="deer" asp-action="Index">Santa`s Raindeers</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <main role="main" class="pb-3 main">
            <div class="container">
                @RenderBody()
            </div>
        </main>


        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2025 - Sana06 - <a  asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
    </div>
   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/deer/Create.cshtml
@model Sana06.Models.deer

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>deer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control input" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Years" class="control-label"></label>
                <input asp-for="Years" class="form-control input" />
                <span asp-validation-for="Years" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="favorite_threat" class="control-label"></label>
                <input asp-for="favorite_threat" class="form-control input" />
                <span asp-validation-for="favorite_threat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/deer/Delete.cshtml
@model Sana06.Models.deer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>deer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Years)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Years)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.favorite_threat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.favorite_threat)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/deer/Details.cshtml
@model Sana06.Models.deer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>deer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Years)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Years)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.favorite_threat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.favorite_threat)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/deer/Edit.cshtml
@model Sana06.Models.deer

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>deer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control input" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Years" class="control-label"></label>
                <input asp-for="Years" class="form-control input" />
                <span asp-validation-for="Years" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="favorite_threat" class="control-label"></label>
                <input asp-for="favorite_threat" class="form-control input" />
                <span asp-validation-for="favorite_threat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/deer/Index.cshtml
@model IEnumerable<Sana06.Models.deer>

@{
    ViewData["Title"] = "Santa`s Raindeer";
}

<h1>Santa`s Raindeer</h1>

<p>
    <a class="link" asp-action="Create">add raindeer</a>
</p>
<table class="table table-color">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Years)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.favorite_threat)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Years)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.favorite_threat)
            </td>
            <td>
                <a class="link" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a class="link" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a class="link" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>